import type { Exhibit, MuseumBackup } from './model';
const stories: Omit<Exhibit, 'id' | 'createdAt' | 'updatedAt' | 'evidence' | 'tags'>[] = [
  {
    title: '我让一座桥稳了下来',
    occurredOn: '2026-09-12',
    datePrecision: 'day',
    theme: 'craft',
    artifact: 'bridge',
    palette: 'bronze',
    summary: '把零散的处理方式，变成可复用的流程。',
    context: '几位伙伴一起维护一个小项目。同样的问题，每次都要重新讨论解决办法。',
    challenge: '问题并不总能复现，经验又散落在不同人的笔记里。我们需要一条大家都走得通的路。',
    actions: [
      '把遇到过的问题按发生条件整理在一起。',
      '为关键步骤补上检查清单，并和伙伴一起走了一遍。',
      '记录仍然不确定的地方，留出继续修正的入口。',
    ],
    outcome: '我们有了一份能复用的处理流程。它还不完美，但下一次遇到问题时，不必从头摸索。',
    meaning: '可靠不是一次漂亮的解决，而是把走过的路留给后来的人。',
    noteToSelf: '你当时没有全部答案，但你一步一步把事情弄清楚了。',
  },
  {
    title: '我把想法放到了世界上',
    occurredOn: '2026-08-24',
    datePrecision: 'day',
    theme: 'craft',
    artifact: 'crystal',
    palette: 'midnight',
    summary: '第一个作品并不完整，但它终于能被打开。',
    context: '那个想法在笔记里放了很久。我一直想做一个小小的阅读工具。',
    challenge: '每次动手都会发现新的功能想加进去，迟迟没有能交给别人使用的版本。',
    actions: [
      '只留下最想解决的一个问题。',
      '做出一个能读完一篇文章的版本。',
      '把链接发给朋友，听他们说哪里不明白。',
    ],
    outcome: '第一个版本终于可以打开了。我记下反馈，决定下一次只改最影响体验的地方。',
    meaning: '把一个不完整的想法交给世界，是开始学习的方式。',
    noteToSelf: '先让它存在，再慢慢让它变好。',
  },
  {
    title: '那次，我把问题讲清楚了',
    occurredOn: '2026-07',
    datePrecision: 'month',
    theme: 'growth',
    artifact: 'lighthouse',
    palette: 'sage',
    summary: '我开始把判断与取舍说给别人听。',
    context: '讨论一个新方案时，大家看见的是不同的问题。我想试着把这些视角放在同一张纸上。',
    challenge: '我担心自己的判断不够成熟，也不知道如何表达还没有答案的部分。',
    actions: [
      '把已知事实和个人推测分开。',
      '画出两条可选路径，以及各自需要放弃的东西。',
      '在讨论时明确说出仍需验证的假设。',
    ],
    outcome: '这次讨论有了可以继续推进的共识。并非每个人都同意，但大家知道了彼此在担心什么。',
    meaning: '表达不只是证明自己，也可以是帮助大家看清方向。',
    noteToSelf: '不确定也可以被诚实地说出来。',
  },
  {
    title: '一个没有被工作占走的下午',
    occurredOn: '2026-06-14',
    datePrecision: 'day',
    theme: 'relationships',
    artifact: 'twin-stars',
    palette: 'bronze',
    summary: '我把手机放下，认真陪伴身边的人。',
    context: '周末，我们原本只打算一起出去走一会儿。天气很好，公园里的树影落在小路上。',
    challenge: '我习惯随时查看消息，即使人坐在一起，心里还在想着没有做完的事。',
    actions: [
      '把手机调成静音，放进包里。',
      '听对方讲最近在意的小事。',
      '沿着不熟悉的小路慢慢走，坐下来一起吃了点东西。',
    ],
    outcome: '我们度过了一个普通、轻松的下午。我记得那天说的话，也记得树叶的光。',
    meaning: '陪伴不必发生在特别的日子，完整地在场就很珍贵。',
    noteToSelf: '这些没有产出的时刻，也是生活。',
  },
  {
    title: '我重新穿上了跑鞋',
    occurredOn: '2026-05-09',
    datePrecision: 'day',
    theme: 'wellbeing',
    artifact: 'mountain',
    palette: 'sage',
    summary: '从一次短跑开始，找回身体的节奏。',
    context: '有一阵子没有运动了。跑鞋一直在门口，我却总觉得应该等状态更好再开始。',
    challenge: '我害怕自己退步，也不想把运动变成另一个必须完成的任务。',
    actions: [
      '选了一条离家很近的小路。',
      '跑不动时就走，不给自己规定成绩。',
      '回来后喝水、伸展，留意身体的感受。',
    ],
    outcome: '我完成了一次很短的跑步。速度并不快，但那晚身体更松弛，我也更愿意再出去一次。',
    meaning: '重新开始可以很小，身体不需要我证明什么。',
    noteToSelf: '你的节奏，可以由你自己决定。',
  },
  {
    title: '我学会先停下来',
    occurredOn: '2026-04',
    datePrecision: 'month',
    theme: 'wellbeing',
    artifact: 'lighthouse',
    palette: 'midnight',
    summary: '疲惫的时候，恢复也是一个值得尊重的决定。',
    context: '接连几天忙碌后，我开始在小事上失去耐心，却还想把剩下的事情全部做完。',
    challenge: '停下来让我感到不安，仿佛休息意味着没有尽力。',
    actions: [
      '承认当天的精力已经不够。',
      '把需要继续的事情写下来，安排到之后。',
      '离开电脑，吃了一顿完整的晚饭，早点休息。',
    ],
    outcome: '事情没有凭空消失。但休息后，我能更清楚地分辨先做什么，也更愿意认真听别人说话。',
    meaning: '照顾自己，是让我能走得更久的一个判断。',
    noteToSelf: '不必用耗尽自己来证明认真。',
  },
];
export const demoMuseum: MuseumBackup = {
  schemaVersion: 1,
  exportedAt: '2026-10-01T00:00:00.000Z',
  owner: { name: 'remy', introduction: '有些路，当时只顾着走。\n回头才发现，它们早已留下了光。' },
  exhibits: stories.map((s, i) => ({
    ...s,
    id: `00000000-0000-4000-8000-${String(i + 1).padStart(12, '0')}`,
    createdAt: '2026-10-01T00:00:00.000Z',
    updatedAt: '2026-10-01T00:00:00.000Z',
    evidence: [],
    tags: [],
  })),
  featuredIds: [
    '00000000-0000-4000-8000-000000000001',
    '00000000-0000-4000-8000-000000000003',
    '00000000-0000-4000-8000-000000000004',
  ],
};
